name: theBlog
favicon: null
layout_spectrum: 0.30897283158265054
typography_spectrum: 0.3716396437957883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0ebfc'
    - '#9baf8b'
    - '#010101'
    - '#28431c'
    - '#cb8271'
  brandStrength: 0.6875
  lightness: 0.45702012442052364
  saturation: 0.7394655654206872
  rhythmicContrast: 0.6404823279008269
purpose: []
